version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  azure-aks: circleci/azure-aks@0.3.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build:
    executor:
      name: docker/docker
      tag: "3.6"
    parameters:
      target:
        type: string
    environment:
      TARGET: <<parameters.target>>
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: | 
            echo 'export PROJECT_TARGET="${TARGET/-/_}"' >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg CMAKE_PROJECT_TARGET=${PROJECT_TARGET}_standalone --build-arg PROJECT_TARGET=${PROJECT_TARGET} -t emregistery.azurecr.io/entrance_monitor:<< parameters.target >> .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS emregistery.azurecr.io
            docker push emregistery.azurecr.io/entrance_monitor:<< parameters.target >>
  create-deployment:
    executor: azure-aks/default
    parameters:
      cluster-name:
        description: |
          Name of the AKS cluster
        type: string
      resource-group:
        description: |
          Resource group that the cluster is in
        type: string
      target:
        description: |
          Project target
        type: string
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          perform-login: true
          resource-group: << parameters.resource-group >>
      - kubernetes/create-or-update-resource:
          namespace: entrance-monitor
          get-rollout-status: true
          resource-file-path: deployment/<< parameters.target>>-deployment.yaml
          resource-name: deployment/<< parameters.target >>
workflows:
  build-and-deploy:
    jobs:
      - build:
          name: build_<< matrix.target >>
          context: entrance-monitor
          filters:
            branches:
              only: /^(develop|production|hotfix|release).*$/ # TODO: split develop/production,hotfix/release environments
          matrix:
            parameters:
              target: [ "stream-obtainer", "object-detector", "blocking-computation", "results-aggregator" ]
      - create-deployment:
          cluster-name: entrance-monitor-cluster
          requires:
              - deploy_<< matrix.target >>
          resource-group: entrance-monitor
          context: entrance-monitor
          matrix:
            parameters:
              target: [ "stream-obtainer", "object-detector", "blocking-computation", "results-aggregator" ]