#ARG CUDA="11.7.0"
#ARG UBUNTU="20.04"
#ARG OPENCV="4.6.0"

FROM jamalabo1/entrance_monitor:builder as builder
FROM jamalabo1/entrance_monitor:gpu-opencv as runtime
COPY --from=builder /opt/vcpkg /opt/vcpkg
ENV CMAKE_TOOLCHAIN_FILE="/opt/vcpkg/scripts/buildsystems/vcpkg.cmake"