apiVersion: apps/v1
kind: Deployment
metadata:
  name: object_detector
  namespace: entrance-monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: object-detector
  template:
    metadata:
      labels:
        app: object-detector
    spec:
      nodeSelector:
        kubernetes.io/os: linux

      containers:
        - name: object-detector
          image: emregistery.azurecr.io/entrance_monitor:object_detector
          imagePullPolicy: Always
          ports: []
          env:
            - name: AZURE_KEYVAULT_URL
              valueFrom:
                secretKeyRef:
                  name: entrance-monitor-secrets
                  key: AZURE_KEYVAULT_URL
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: entrance-monitor-secrets
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: entrance-monitor-secrets
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: entrance-monitor-secrets
                  key: AZURE_TENANT_ID
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G
